### ISSUE TITLE
Matching root subpaths with an exception of e.g. /cms

### ISSUE THREAD

**Issue by Eccenux** [wanderview/service-worker-scope-pattern-matching#12]
I believe a quite common case is to have a public web page on root (/) and some CMS on a sub path (e.g. /cms, /admin). Effectively those can be completely separate applications.

Note that the public page typically would also have routes like "/product/123/title" or "/blog/2020/my-article".

So it would be useful to have a separate serviceWorker for both applications. And it would be useful to exclude "/cms/\*" instead of defining all paths for the main app.

**Comment by wanderview** [comment]
The main blocker for adding exclusions is supporting it for PWAs on android devices.  Currently the OS does not make it possible for a URL intent to apply a filter that has an exclusion like this.  Therefore this proposal is not pursuing exclusions at this time.  If the OS changes we could add them in the future.

Note, however, there is a workaround today.  You can register a service worker with no fetch handler for "/cms/*" and it will take precedence over other, more general registrations.  While not as convenient, this is an existing method to exclude a particular subpath.

**Comment by Eccenux** [comment]
OK. That seems fine than. The workaround would work for me.
