### ISSUE TITLE
Does /foo/?* prevent /foobar from matching?

### ISSUE THREAD

**Issue by mgiuca** [wanderview/service-worker-scope-pattern-matching#2]
Based on the description that "The `?` pattern character makes the preceding character optional" and "The `*` pattern character matches zero or more characters", it would seem that a path of `"/foo/?*"` would match `"/foo"`, `"/foo/"`, `"/foobar"`, and `"/foo/bar"`, basically it's allowed to either have a slash, or not, and it's allowed to have anything after the slash.

I think the intention is that `"/foobar"` would not be matched by this (otherwise why not just write `"/foo*"`?). It's not immediately obvious that this would be blocked.

It's possible that this is explained by the "non-variable prefix" stuff, but I haven't fully understood that from a cursory reading of the explainer. If so, it should maybe be written to explain that explicitly and up front.

**Comment by wanderview** [comment]
Yes, it will not match `/foobar`.  I tried to express this by stating it implied a "path break".  For example, there is a part that says:

```
In addition, there is a context-specific behavior:

* In a path pattern, the /? sequence would indicate a break between path segments.
```

We could also add some other way to signal a path break, but I don't have a good suggestion at the moment.

**Comment by mgiuca** [comment]
Since you had your list of restrictions (e.g., `*` can only appear at the end), I was thinking, why not require that `/?` can also only appear at the end. Since I don't see any reason to have it in the middle of a pattern, e.g., `"/foo/?bar"` means literally the same thing as `"/foo/bar"` (since `/?` signals a path break).

Thus you could define it more simply as that there are four possible ending sequences:

* (nothing): Match this exact path only.
* `/?`: Match this path either with or without a trailing slash, and no further path segments.
* `*`: Match any string with this path as a suffix (like classic scope match).
* `/?*`: Match either this exact path without a trailing slash and no further path segments, or this path with a trailing slash and optionally more path segments.

Another option is to just literally go with regex syntax but make it restricted to just these four cases at the end of the pattern, rather than a generic regex parse:

* (nothing)
* `/?`
* `.*`
* `(/.*)?`

It's more verbose and a little harder to parse, but everyone understands what it means without further explanation required. Major downside is needing to escape `.` elsewhere in the pattern.

**Comment by wanderview** [comment]
First, keep in mind the explainer is trying to lock down use cases and is not intended to fully specify details.

> Since you had your list of restrictions (e.g., * can only appear at the end),

That restriction is only for scopes.  The intent was that URLPattern could have in-fix wildcards when used in other contexts.

> why not require that /? can also only appear at the end

There could be restrictions on where it appears.  As you say, we could throw for `/foo/?bar`.

We could also switch to handling path breaks differently like using the implicit segment delimiter approach in path-to-regexp:

https://github.com/pillarjs/path-to-regexp/

> Another option is to just literally go with regex syntax

That's possible.  Some libraries use this pattern style.

I don't have a strong opinion on the exact syntax and would defer to people more in tune with web developer preferences.  I want to get agreement on the use cases before diving into those details, though.

**Comment by wanderview** [comment]
The explainer has been revamped to align with path-to-regexp syntax.  This supports the original question here of matching "/foo" and "/foo/baz", but not "/foobar" via its optional prefix feature.  The pattern in this case would be "/foo/*?".  The "?" modifier makes the wildcard and the preceeding "/" optional.

I'm going to close this for now.  Feel free to open a new issue regarding the new approach if there is more to discuss.  Thanks.
