### ISSUE TITLE
Why the limit to one search parameter?

### ISSUE THREAD

**Issue by mgiuca** [wanderview/service-worker-scope-pattern-matching#3]
> At most one search parameter pattern.

I'm curious as to the rationale behind this limit. It seems potentially useful to be able to allow any number of search param restrictions.

I would imagine that these search parameters act as additional constraints, i.e., there is no way to make a URL that matches a particular pattern, but adding extra query params to the URL fails to match. However, multiple search parameter patterns would require a matching URL to feature ALL of those search parameters.

**Comment by wanderview** [comment]
It was mainly to limit complexity to avoid pathological performance problems during navigation scope lookups.

Its true that using an AND logic would avoid some complexity here, but that is really only true if we are requiring fixed parameters.  The explainer currently proposed allowing patterns in parameter names and values.  I think combining multiple parameters with variable names/values could still be quite complex to evaluate in a reasonable amount of CPU time.

**Comment by fallaciousreasoning** [comment]
It also opens the door to questions about more complicated search params, like arrays.

```js
let params = new URLSearchParams('foo=bar&foo=qux');
console.log(params.getAll('foo')); // => ['bar', 'qux']
```

> Note: I think we should try and avoid supporting them, but it's worth considering while we're thinking about it. It definitely seems worse for performance.

**Comment by wanderview** [comment]
The explainer has been updated to no longer attempt to support arbitrary query parameter matching.  I think this is OBE.
