### ISSUE TITLE
Web NFC does some URL matching, would be good to coordinate

### ISSUE THREAD

**Issue by kenchris** [wanderview/service-worker-scope-pattern-matching#6]
https://w3c.github.io/web-nfc/#url-pattern-match-algorithm

**Comment by wanderview** [comment]
Thanks for filing this.  I was not aware of the URL matching in Web NFC.  I'll consider what we can do to align here.

If we do end up exposing something like URLPattern, do you think Web NFC would be able to updated to use it?  That would strengthen the argument for creating a web platform primitive like this.

**Comment by kenchris** [comment]
I don't see why not. This will also make it more clear from user code that we are not doing exact matches

@zolkis

**Comment by zolkis** [comment]
Makes sense.

**Comment by wanderview** [comment]
AFAICT web nfc does not do any matching on search parameters.  Is that correct?

**Comment by kenchris** [comment]
Correct, those are not stored in the id field. But in theory I guess they could be

**Comment by kenchris** [comment]
We might want to allow *.example.com support (not just trailing *) to allow optional subdomain names given we that we cannot enforce registrable domain names

**Comment by wanderview** [comment]
@kenchris Does webnfc still support URL matching?  I looked through the latest spec and only saw mime type matching?

**Comment by kenchris** [comment]
Nope, the feedback we got from Origin Trials etc showed that our filtering wasn't flexible enough so developers did it manually.

**Comment by wanderview** [comment]
Ok, going to close this for now then.  Thanks.
