### ISSUE TITLE
Compatibility of future features

### ISSUE THREAD

**Issue by jakearchibald** [wanderview/service-worker-scope-pattern-matching#7]
I like the idea of adding features in future, but I'm not sure how we can do it.

With `/*.(png|jpg)`, this will initially match:

* `/foo.(png%7Cjpg)`
* `/bar.(png%7Cjpg)`

And these will not match:

* `/foo.png`
* `/bar.jpg`

If we later add support for groups, the above reverses. Is that something we can do? It feels like a compatibility issue. Or, will there be a way to opt into new features? Or, will we reserve a set of characters for future use, making `/*.(png|jpg)` throw "not implemented" or somesuch?

**Comment by wanderview** [comment]
I think we probably want to reserve characters like `(`, `)`, `|`, `:`, `+`, etc.

**Comment by jakearchibald** [comment]
Yeah, we could also treat everything within `(` & `)` (or `{` & `}`) as special. Then we can add extensions by switching on the first char within the group. As in `/foo{:bar}` could mean something different to `/foo{!bar}`. Browsers without support would throw at the `{` or the `:`/`!` depending on what they understood.

**Comment by wanderview** [comment]
Rather than try to add features in the future I'm not proposing to implement full path-to-regexp behavior upfront.  I think that addresses this issue since we won't be planning to expand the feature set in the future.
