### ISSUE TITLE
API bikeshedding

### ISSUE THREAD

**Issue by domenic** [wanderview/service-worker-scope-pattern-matching#8]
- `baseUrl` should be `baseURL` per [the URL Standard](https://url.spec.whatwg.org/#url-apis-elsewhere) (but see #1)
- `path` should probably be `pathname` to match `URL` and friends?
- I suggest that `search` be overloaded between a string, an iterable of two-element iterables, or a record, similar to the `URLSearchParams` constructor itself:
  ```js
  new URLPattern({
    ...,
    search: "foo=bar&*=baz"
  });
  
  new URLPattern({
    ...,
    search: [['foo', 'bar'], ['*', 'baz']]
  });
  
  new URLPattern({
    ...,
    search: { foo: 'bar', '*': 'baz' }
  });
  ```

**Comment by fallaciousreasoning** [comment]
- Would `search: "foo=bar&thing=baz"` care about ordering? It definitely seems like it shouldn't, but this might be non-obvious.
- Do you have an example where matching a key as `*` would be useful? Not completely against it but curious where it would be used. Is it a kind of 'we want there to be a query param thing'.
- What's the advantage of the two element iterables? Ease of construction?
- Maybe `search` should be overloadable with a URLSearchParams too?

**Comment by domenic** [comment]
This probably isn't the right issue to ask those questions. I am simply proposing a rearranging of the API surface to match the platform precedents; all those features you discuss already exist in the explainer.

**Comment by wanderview** [comment]
I believe the revamped approach in the updated explainer addresses these items.
